# Generated by Django 4.2.7 on 2025-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_permission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('sales', 'Ventes'), ('products', 'Produits'), ('stocks', 'Stocks'), ('tables', 'Tables'), ('orders', 'Commandes'), ('kitchen', 'Cuisine'), ('reports', 'Rapports'), ('analytics', 'Analyses'), ('users', 'Utilisateurs'), ('suppliers', 'Fournisseurs'), ('expenses', 'Dépenses'), ('settings', 'Paramètres')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
