# Generated by Django 4.2.7 on 2025-11-04 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_alter_sale_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de crédit (FBu)')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde actuel (FBu)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('closed', 'Fermé')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Crédit',
                'verbose_name_plural': 'Comptes Crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debt', 'Dette (vente à crédit)'), ('payment', 'Paiement'), ('adjustment', 'Ajustement')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FBu)')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('bank_transfer', 'Virement bancaire')], max_length=20, null=True, verbose_name='Méthode de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credits.creditaccount')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Transaction Crédit',
                'verbose_name_plural': 'Transactions Crédit',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(verbose_name='Date de relance')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant dû (FBu)')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('acknowledged', 'Accusée')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='credits.creditaccount')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relance Crédit',
                'verbose_name_plural': 'Relances Crédit',
                'ordering': ['-reminder_date'],
            },
        ),
    ]
