GRANT ALL PRIVILEGES ON DATABASE barstock_db TO barstock_user;
GRANT ALL ON SCHEMA public TO barstock_user;
GRANT CREATE ON SCHEMA public TO barstock_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO barstock_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO barstock_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO barstock_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO barstock_user;
