services:
  # Backend API Django
  - type: web
    name: barstock-api
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT barstock_api.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: barstock-db
          property: connectionString

  # Base de données PostgreSQL
databases:
  - name: barstock-db
    region: frankfurt
    plan: free
    databaseName: barstock_db
    user: barstock_user
