-- Script pour recréer les tables expenses avec la bonne structure

-- Supprimer les anciennes tables
DROP TABLE IF EXISTS expenses_expense CASCADE;
DROP TABLE IF EXISTS expenses_expensebudget CASCADE;
DROP TABLE IF EXISTS expenses_expensecategory CASCADE;

-- Créer ExpenseCategory
CREATE TABLE "expenses_expensecategory" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL UNIQUE,
    "category_type" varchar(20) NOT NULL,
    "description" text NOT NULL,
    "budget_monthly" numeric(12, 2) NULL,
    "is_active" boolean NOT NULL,
    "requires_approval" boolean NOT NULL,
    "approval_threshold" numeric(12, 2) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

-- Créer ExpenseBudget
CREATE TABLE "expenses_expensebudget" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "year" integer NOT NULL,
    "month" integer NOT NULL,
    "budget_amount" numeric(12, 2) NOT NULL,
    "actual_amount" numeric(12, 2) NOT NULL,
    "notes" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "category_id" bigint NOT NULL
);

-- Créer Expense
CREATE TABLE "expenses_expense" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "description" varchar(255) NOT NULL,
    "amount" numeric(12, 2) NOT NULL,
    "payment_method" varchar(20) NOT NULL,
    "payment_reference" varchar(100) NOT NULL,
    "receipt_number" varchar(100) NOT NULL,
    "receipt_file" varchar(100) NULL,
    "expense_date" date NOT NULL,
    "due_date" date NULL,
    "status" varchar(20) NOT NULL,
    "approved_at" timestamp with time zone NULL,
    "rejection_reason" text NOT NULL,
    "notes" text NOT NULL,
    "is_recurring" boolean NOT NULL,
    "recurrence_period" varchar(20) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "approved_by_id" bigint NULL,
    "category_id" bigint NOT NULL,
    "created_by_id" bigint NOT NULL,
    "supplier_id" bigint NULL
);

-- Index et contraintes
CREATE INDEX "expenses_expensecategory_name_ac0768b4_like" ON "expenses_expensecategory" ("name" varchar_pattern_ops);

ALTER TABLE "expenses_expensebudget" ADD CONSTRAINT "expenses_expensebudget_category_id_year_month_fc1f386a_uniq" UNIQUE ("category_id", "year", "month");
ALTER TABLE "expenses_expensebudget" ADD CONSTRAINT "expenses_expensebudg_category_id_4aea1b60_fk_expenses_" FOREIGN KEY ("category_id") REFERENCES "expenses_expensecategory" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "expenses_expensebudget_category_id_4aea1b60" ON "expenses_expensebudget" ("category_id");

ALTER TABLE "expenses_expense" ADD CONSTRAINT "expenses_expense_approved_by_id_8d0bf499_fk_accounts_user_id" FOREIGN KEY ("approved_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "expenses_expense" ADD CONSTRAINT "expenses_expense_category_id_aa33bbdd_fk_expenses_" FOREIGN KEY ("category_id") REFERENCES "expenses_expensecategory" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "expenses_expense" ADD CONSTRAINT "expenses_expense_created_by_id_a2610358_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "expenses_expense" ADD CONSTRAINT "expenses_expense_supplier_id_9e9544d1_fk_suppliers_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "suppliers_supplier" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "expenses_expense_approved_by_id_8d0bf499" ON "expenses_expense" ("approved_by_id");
CREATE INDEX "expenses_expense_category_id_aa33bbdd" ON "expenses_expense" ("category_id");
CREATE INDEX "expenses_expense_created_by_id_a2610358" ON "expenses_expense" ("created_by_id");
CREATE INDEX "expenses_expense_supplier_id_9e9544d1" ON "expenses_expense" ("supplier_id");
CREATE INDEX "expenses_ex_expense_cf8a73_idx" ON "expenses_expense" ("expense_date");
CREATE INDEX "expenses_ex_status_cbb790_idx" ON "expenses_expense" ("status");
CREATE INDEX "expenses_ex_categor_20264a_idx" ON "expenses_expense" ("category_id");
CREATE INDEX "expenses_ex_created_bde1a5_idx" ON "expenses_expense" ("created_by_id");

COMMIT;
