# Generated by Django 4.2.7 on 2025-09-16 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='sound_notifications',
            new_name='auto_refresh_dashboard',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='default_currency_display',
            new_name='default_currency',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='alert_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='compact_dashboard_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='dashboard_refresh_interval',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='inventory_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='order_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='show_dashboard_charts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='time_format',
            field=models.CharField(default='24h', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='Africa/Bujumbura', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='items_per_page',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
