# Generated by Django 4.2.7 on 2025-09-20 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_rename_sound_notifications_userpreferences_auto_refresh_dashboard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='default_currency',
            new_name='default_currency_display',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='alert_notifications',
            new_name='sound_notifications',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='auto_refresh_dashboard',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='compact_dashboard_view',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='dashboard_refresh_interval',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='date_format',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='inventory_notifications',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='order_notifications',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_dashboard_charts',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='sms_notifications',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='time_format',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='items_per_page',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
