# Generated by Django 4.2.7 on 2025-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_add_sound_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='audit_logs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_logout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_print_daily_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_login_attempts',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_printer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_printer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='thermal_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
    ]
