# Generated by Django 4.2.7 on 2025-11-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_systemsettings_audit_logs_systemsettings_auto_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='session_duration',
            field=models.IntegerField(default=1, help_text='Durée de la session en heures'),
        ),
    ]
