# Generated by Django 4.2.7 on 2025-08-25 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU'), ('memory', 'Mémoire'), ('disk', 'Disque'), ('network', 'Réseau'), ('database', 'Base de données'), ('api_response_time', 'Temps de réponse API'), ('active_users', 'Utilisateurs actifs'), ('sales_per_hour', 'Ventes par heure')], max_length=50, verbose_name='Type de métrique')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('unit', models.CharField(help_text='%, MB, ms, etc.', max_length=20, verbose_name='Unité')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Métrique système',
                'verbose_name_plural': 'Métriques système',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='monitoring__metric__495aca_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Sévérité')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acquittée'), ('resolved', 'Résolue')], default='active', max_length=20, verbose_name='Statut')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Valeur seuil')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acquittement")),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Acquittée par')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.systemmetric', verbose_name='Métrique liée')),
            ],
            options={
                'verbose_name': 'Alerte système',
                'verbose_name_plural': 'Alertes système',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='Méthode HTTP')),
                ('response_time', models.FloatField(verbose_name='Temps de réponse (ms)')),
                ('status_code', models.IntegerField(verbose_name='Code de statut')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log de performance',
                'verbose_name_plural': 'Logs de performance',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='monitoring__endpoin_580bc7_idx'), models.Index(fields=['status_code', '-timestamp'], name='monitoring__status__5eaea2_idx')],
            },
        ),
    ]
