# Generated by Django 4.2.7 on 2025-11-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('sales', '0005_alter_sale_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='credits.creditaccount', verbose_name='Compte crédit'),
        ),
    ]
