# Generated by Django 4.2.7 on 2025-11-04 08:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0003_alter_supplier_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('category_type', models.CharField(choices=[('operational', 'Opérationnel'), ('inventory', 'Inventaire/Achats'), ('staff', 'Personnel'), ('utilities', 'Charges fixes'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('other', 'Autres')], default='other', max_length=20, verbose_name='Type de catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('budget_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Budget mensuel alloué à cette catégorie', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Budget mensuel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Catégorie active')),
                ('requires_approval', models.BooleanField(default=False, help_text='Les dépenses de cette catégorie nécessitent une approbation', verbose_name='Nécessite approbation')),
                ('approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text="Montant au-delà duquel l'approbation est requise", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Seuil d'approbation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant budgété')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Montant réel')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='expenses.expensecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Budget de dépense',
                'verbose_name_plural': 'Budgets de dépenses',
                'ordering': ['-year', '-month'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque')], max_length=20, verbose_name='Méthode de paiement')),
                ('payment_reference', models.CharField(blank=True, help_text='Numéro de transaction/chèque/référence', max_length=100, verbose_name='Référence de paiement')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de reçu')),
                ('receipt_file', models.FileField(blank=True, help_text='Scan du reçu/facture', null=True, upload_to='expenses/receipts/%Y/%m/', verbose_name='Fichier reçu')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('due_date', models.DateField(blank=True, help_text="Date d'échéance si paiement différé", null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], default='pending', max_length=20, verbose_name='Statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_recurring', models.BooleanField(default=False, help_text='Dépense récurrente (loyer, abonnements, etc.)', verbose_name='Dépense récurrente')),
                ('recurrence_period', models.CharField(blank=True, choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20, null=True, verbose_name='Période de récurrence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='suppliers.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'), models.Index(fields=['status'], name='expenses_ex_status_cbb790_idx'), models.Index(fields=['category'], name='expenses_ex_categor_20264a_idx'), models.Index(fields=['created_by'], name='expenses_ex_created_bde1a5_idx')],
            },
        ),
    ]
